@baseUrl = http://localhost:3000
@spotId = adfc9061-2ea2-4616-b577-8b0a5deaa0db

@imageId = 46d3320f-bc4a-49c8-8270-be608a316abb

### Health check
GET {{baseUrl}}

# ========================== AUTH ==========================
### REGISTRO
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "retr0lbb",
    "email": "retr0lbb@mail.com",
    "password": "123123"
}

### login
# @name login
POST  {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "retr0lbb@mail.com",
    "password": "123123"
}


# ========================== SPOT ==========================
### Criar spot
POST {{baseUrl}}/spots
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "lat": "4.2726784",
    "lon": "73.5132004",
    "alias": "Lake Winston",
    "description": "Vista do lago winston na escocia. vista de cima do lago ideal para um piquenique",
    "address": "R. Royal vista, 1829. Aurora lane"
}

### Buscar spots por raio
GET {{baseUrl}}/spots?lat=4.2766985&lon=73.51321006&radius=5000

### Atualizar spot
PUT {{baseUrl}}/spots/{{spotId}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "alias": "Pico da neblina"
}

### Deletar spot
DELETE {{baseUrl}}/spots/{{spotId}}


# ========================== IMAGENS DO SPOT ==========================
### Gerar presigned URL para upload
# @name presigned
POST {{baseUrl}}/spots/{{spotId}}/image
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "mimeType": "image/jpg",
    "sizeBytes": 15728640,
    "originalName": "reggie.webp",
    "latitude": 4.2726784,
    "longitude": 73.5132004
}

### Upload da imagem (cole a uploadUrl retornada acima)
PUT {{presigned.response.body.uploadUrl}}
Content-Type: image/jpg

< ./reggie.webp

### Confirmar upload
POST {{baseUrl}}/spots/{{spotId}}/image/{{presigned.response.body.imageId}}/confirm

### Listar imagens do spot
GET {{baseUrl}}/spots/{{spotId}}/images

### DELETE AN IMAGE FROM A SPOT
DELETE  {{baseUrl}}/spots/{{spotId}}/images/{{imageId}}
Authorization: Bearer {{login.response.body.accessToken}}

# ========================== USUARIOS ==========================
### PEGA A INFORMACAO DOS USUARIOS
GET {{baseUrl}}/users
Authorization: Bearer {{login.response.body.accessToken}}

###
# @name picture
POST {{baseUrl}}/users/picture
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
  "mimeType": "image/webp",
  "sizeBytes": 21024,
  "originalName": "reggie.webp"
}

### Upload da imagem
PUT http://localhost:9000/spots/profile/b3d9f6a0-ed5c-4136-9782-f980b5742aa7/70ecee44-eae2-4c3c-ba3b-96586f14759a.webp?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=minioadmin%2F20260806%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260806T214614Z&X-Amz-Expires=300&X-Amz-Signature=c8e0ef3d54c1e820c588e77350ec8a1a1da290f9ebb9a222dfee8f101abb2b12&X-Amz-SignedHeaders=host&x-amz-checksum-crc32=AAAAAA%3D%3D&x-amz-sdk-checksum-algorithm=CRC32&x-id=PutObject
Content-Type: image/webp

< ./reggie.webp