@baseUrl = http://localhost:3000
@spotId = 3128d784-59fd-4644-aa09-63c77a9c3fbd

@imageId = c5dad938-1197-4eb8-a775-a1d858cad772

### Health check
GET {{baseUrl}}

# ========================== AUTH ==========================
### REGISTRO
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "retr0lbb",
    "email": "retr0lbb@mail.com",
    "password": "123123"
}

### login
# @name login
POST  {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "retr0lbb@mail.com",
    "password": "123123"
}


# ========================== SPOT ==========================
### Criar spot
POST {{baseUrl}}/spots
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "lat": "4.2726784",
    "lon": "73.5132004",
    "alias": "Lake Winston",
    "description": "Vista do lago winston na escocia. vista de cima do lago ideal para um piquenique",
    "address": "R. Royal vista, 1829. Aurora lane"
}

### Buscar spots por raio
GET {{baseUrl}}/spots?lat=4.2766985&lon=73.51321006&radius=5000

### Atualizar spot
PUT {{baseUrl}}/spots/{{spotId}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "alias": "Pico da neblina"
}

### Deletar spot
DELETE {{baseUrl}}/spots/{{spotId}}


# ========================== IMAGENS DO SPOT ==========================
### Gerar presigned URL para upload
# @name presigned
POST {{baseUrl}}/spots/{{spotId}}/image
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "mimeType": "image/jpg",
    "sizeBytes": 15728640,
    "originalName": "reggie.webp",
    "latitude": 4.2726784,
    "longitude": 73.5132004
}

### Upload da imagem (cole a uploadUrl retornada acima)
PUT {{presigned.response.body.uploadUrl}}
Content-Type: image/jpg

< ./reggie.webp

### Confirmar upload
POST {{baseUrl}}/spots/{{spotId}}/image/{{presigned.response.body.imageId}}/confirm

### Listar imagens do spot
GET {{baseUrl}}/spots/{{spotId}}/images

### DELETE AN IMAGE FROM A SPOT
DELETE  {{baseUrl}}/spots/{{spotId}}/images/{{imageId}}
Authorization: Bearer {{login.response.body.accessToken}}

# ========================== USUARIOS ==========================
### PEGA A INFORMACAO DOS USUARIOS
GET {{baseUrl}}/users
Authorization: Bearer {{login.response.body.accessToken}}

###
# @name picture
POST {{baseUrl}}/users/picture
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
  "mimeType": "image/webp",
  "sizeBytes": 21024,
  "originalName": "reggie.webp"
}

### Upload da imagem
PUT {{picture.response.body.url}}

< ./reggie.webp