services:
  spots_db:
    image: postgis/postgis:16-3.4
    container_name: spots_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker        # era POSTGRES_USERNAME
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=spotz           # era POSTGRES_DATABASE
    volumes:
      - db_data:/var/lib/postgresql/data   # era /bitnami/postgresql
    restart: no

volumes:
  db_data: